name: Trigger auto deployment for agstudio

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/agstudio-AutoDeployTrigger.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for requesting the OIDC JWT Token
      contents: read   # Required for repository read access

    steps:
      # Step 1: Checkout the code
      - name: Checkout the branch
        uses: actions/checkout@v2

      # Step 2: Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AGSTUDIO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGSTUDIO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGSTUDIO_AZURE_SUBSCRIPTION_ID }}

      # Step 3: Build Docker images using docker-compose and push to Azure Container Registry (ACR)
      - name: Build and push container images
        run: |
          # Log in to ACR
          az acr login --name ${{ secrets.AGSTUDIO_ACR_NAME }}

          # Tag and push images using docker-compose
          docker-compose build
          docker-compose push

      # Step 4: Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          # Create or update Azure Container Apps with docker-compose images
          az containerapp create \
            --name agstudio \
            --resource-group DefaultResourceGroup-EUS \
            --environment agstudio-env \
            --image ${{ secrets.AGSTUDIO_ACR_URL }}/agstudio:${{ github.sha }} \
            --target-port 8081 \
            --ingress external \
            --cpu 0.5 --memory 1.0Gi
